### ISSUE TITLE
Compilation issue in index.d.ts

### ISSUE THREAD

**Issue by shubhamatul** [phovea/phovea_clue#112]
Hi, 
I am using node 6.10.2, npm3.10.10
when running "npm test" command, it is giving following error on console:
 
```
node_modules/@types/lodash/index.d.ts(11587,21): error TS1005: ']' expected.
node_modules/@types/lodash/index.d.ts(11587,22): error TS1005: ';' expected.
node_modules/@types/lodash/index.d.ts(11587,23): error TS1128: Declaration or statement expected.
node_modules/@types/lodash/index.d.ts(11587,33): error TS1005: ']' expected.
node_modules/@types/lodash/index.d.ts(11587,34): error TS1005: ')' expected.
node_modules/@types/lodash/index.d.ts(11587,35): error TS1128: Declaration or statement expected.
node_modules/@types/lodash/index.d.ts(11587,37): error TS1128: Declaration or statement expected.
node_modules/@types/lodash/index.d.ts(19580,1): error TS1128: Declaration or statement expected.
```

Please provide your suggestion.

**Comment by sgratzl** [comment]
there is a recent update in the master branch, migrating to the last develop one. Pleaes update and try again

**Comment by shubhamatul** [comment]
@sgratzl Thank you so much
I have taken the pull using: git clone -b develop https://github.com/phovea/phovea_clue.git
and it works for me.
Now, I am able to build the project using npm.

**Comment by thinkh** [comment]
@shubhamatul is there any update or could you please provide more information how we can reproduce the error?

**Comment by sgratzl** [comment]
can't reproduce
