### ISSUE TITLE
`@types/handlebars` version causes build errors

### ISSUE THREAD

**Issue by gfrogat** [phovea/phovea_clue#130]
* Release number or git hash: 921409de073f4329c09a4602622e87d816de266f
* Web browser version and OS:  macOS 10.13.1
* Environment (local or deployed): local

### Steps to reproduce

1. clone project master branch and install dependencies
```
git clone https://github.com/phovea/phovea_clue.git
npm install
```
2. run tests
`npm test`

### Observed behavior
* build fails due to errors with `@types/handlebars`
```
node_modules/@types/handlebars/index.d.ts(22,31): error TS1005: ',' expected.
node_modules/@types/handlebars/index.d.ts(24,32): error TS1005: ',' expected.
node_modules/@types/handlebars/index.d.ts(99,40): error TS1005: ',' expected.
```

### Expected behavior
* tests run without any errors

### Fixes
* Option1: updating `typescript` to version 2.3 resolves the problem
```
npm install typescript@2.3
```

* Option2: keep `typescript@2.2`, remove the `node_modules/@types/handlebars` and install `@types/handlebars@4.0.33` which resolves the compilation issues.
```
rm -rf rm node_modules/@types/handlebars 
npm install @types/handlebars@4.0.33
```

**Comment by thinkh** [comment]
@gfrogat you are working with the master branch. We usually work with the develop branch.

@sgratzl Can you/we release the deploy branch as new stable version to avoid confusions?

**Comment by thinkh** [comment]
I tried the most recent commit https://github.com/phovea/phovea_clue/commit/336072e87ec8f6054cead9f64c6830897fb7f076 from the master branch. All web test passed now without errors.
