### ISSUE TITLE
Disable undo functionality (via `Ctrl + Z`) when focus is set to an input field

### ISSUE THREAD

**Issue by sgratzl** [phovea/phovea_clue#135]
**Steps to reproduce**
1. Goto https://ordino.caleydoapp.org/
2. Do some actions
3. Open a modal (e.g., persist session modal)
4. Type some words to the title input field
5. Press `Ctrl + Z`
6. Instead of reverting the input the listener for CLUE is triggered

![ordino-bug-ctrl-z](https://user-images.githubusercontent.com/5851088/36321326-b9868f94-1349-11e8-9787-f77892ab7fce.gif)

Normal behavior shown at Google:

![ordino-regular-ctrl-z-behavior](https://user-images.githubusercontent.com/5851088/36321337-c5869866-1349-11e8-9b20-12d2b484fcae.gif)

**Supposed behavior**
The undo behavior schould be disabled when an input field has the focus

**Comment by thinkh** [comment]
The same applies do the keyboard shortcut `Ctrl + Shift + Left` for highlighting a whole word. In the current version this shortcut opens the Story side panel.

**Comment by sgratzl** [comment]
feel free to add more node source types at https://github.com/phovea/phovea_clue/commit/4000019444a0847e897db3c221157cb3f151a986#diff-19decb06747e48294325a434016c8a22R96

**Comment by thinkh** [comment]
Nice solution. Thanks. 👍
