### ISSUE TITLE
JQuery missing in package.json

### ISSUE THREAD

**Issue by keckelt** [phovea/phovea_clue#192]
* Release number or git hash: develop

There are jquery imports in:
```
src/storyvis.ts
20:import * as $ from 'jquery';

src/provvis.ts
7:import * as $ from 'jquery';

src/ACLUEWrapper.ts
135:      // lazy jquery
136:      System.import('jquery').then(($: JQueryStatic) => {

src/menu/ProvenanceGraphMenu.ts
8:import * as $ from 'jquery';
```

but jquery is not in the package.json.

---
I'm getting a errors for these jquery typings with my version (3.5.0): https://github.com/phovea/phovea_clue/pull/190

**Comment by anita-steiner** [comment]
will come through phovea_ui
