### ISSUE TITLE
implement a very simple demonstration example

### ISSUE THREAD

**Issue by ngehlenborg** [phovea/phovea_clue#95]
It should show how one can set up CLUE with a very basic view component (@mccalluc  suggested a text box, it could also be a very basic scatter plot or the heatmap) with two event types that get tracked, register said event types, and how to design the view component to be able to deal with the states stored in the provenance graph (how to store state and how to restore). 

I guess the advantage of the text box example would be that it would not distract with unnecessary crud related to the visualization component. The advantage of the scatter plot or heatmap would be that it could demonstrate how to implement storing and restoring of state.

**Comment by ngehlenborg** [comment]
I should add that ideally this example would also demonstrate how to use the `phovea.js` version of the framework and a the simplest server setup possible (ideally launched by calling the Python webserver from the command line).

**Comment by sgratzl** [comment]
phovea_clue is not part of the phovea_bundle_lib

**Comment by ngehlenborg** [comment]
@sgratzl - That's a different question, see #96.

**Comment by sgratzl** [comment]
https://github.com/sgratzl/clue_hello_world a simple application to keep track of copying a text field to the right side. 

(inplace editing is more difficult, since usually the action should perform the action, like by clicking a button)

**Comment by sgratzl** [comment]
really poor man **provenance** hello world: http://bl.ocks.org/sgratzl/f5e23207a83cc6f159184a85765db476

**Comment by ngehlenborg** [comment]
That's neat. How did you do this? Did you address #96 and add clue to the library bundle?

Where is the provenance being stored?

**Comment by sgratzl** [comment]
> That's neat. How did you do this? Did you address #96 and add clue to the library bundle?

the example just uses just the core which includes the provenance graph logic. However, clue is more: the visual representation, the provenance graph id encoded in url, ...
 
> Where is the provenance being stored?

main memory: https://github.com/phovea/phovea_core/blob/master/src/provenance.ts#L1979

**Comment by ngehlenborg** [comment]
Where the CLUE backend implemented and how would I configure the JS code in your block to use the backend rather than memory?

**Comment by sgratzl** [comment]
> Where is the CLUE backend implemented and how would I configure the JS code in your block to use the backend rather than memory?

what do you mean with CLUE backend?

**Comment by sgratzl** [comment]
btw. since this issue is fixed, please close it.

**Comment by ngehlenborg** [comment]
CLUE backend = where do you store the provenance graph so that it can be retrieved later or shared with others?

**Comment by sgratzl** [comment]
> CLUE backend = where do you store the provenance graph so that it can be retrieved later or shared with others?

a provenance graph is just a graph, see https://github.com/phovea/phovea_core/blob/master/src/graph.ts. This modules implements different graph stores. MemoryGraph = main memory, LocalStorageGraph = localStorage, and RemoteStorageGraph = changes are pushed to the server via POST requests.

**Comment by ngehlenborg** [comment]
How can I initialize the provenance graph to use say the `LocalStorageGraph` or the `RemoteStorageGraph` and where would I find the server component for the `RemoteStorageGraph`?
